# action.yml
name: 'Run Lighthouse CI on Shopify theme'
branding:
  icon: shopping-bag
  colour: green
description: 'Run Lighthouse CI on Shopify themes directly from GitHub'
inputs:
  access_token:
    description: 'Custom app access token'
    # required: false because you can still authenticate with private
    # app credentials
    required: false
  store:
    description: '<domain>.myshopify.com URL'
    required: true
  password:
    description: 'Password-protected shop password'
    required: false
  product_handle:
    description: 'Product handle for product page test (default: first product).'
    required: false
  collection_handle:
    description: 'Collection handle for collection page test (default: first collection).'
    required: false
  theme_root:
    description: 'The root folder for the theme files that will be uploaded (default: ".")'
    required: false
    default: '.'
  lhci_upload_target:
    description: 'The type of target to upload the data to. [choices: "lhci", "temporary-public-storage", "filesystem"] (default: "temporary-public-storage")'
    required: false
  lhci_server_url:
    description: '[lhci only] The base URL of the LHCI server where results will be saved.'
    required: false
  lhci_project_token:
    description: '[lhci only] The Lighthouse CI build token for the project.'
    required: false
  lhci_github_app_token:
    description: 'Lighthouse CI GitHub app token'
    required: false
  lhci_github_token:
    description: 'GitHub personal access token'
    required: false
  lhci_min_score_performance:
    description: 'Minimum performance score'
    required: false
    default: 0.6
  lhci_min_score_accessibility:
    description: 'Minimum accessibility score'
    required: false
    default: 0.9
  app_id:
    description: '(deprecated) Shopify private app ID'
    depreciationMessage: Shopify private apps are deprecated. Use a Custom App `access_token` instead.
    required: false
  app_password:
    description: '(deprecated) Shopify private app password'
    depreciationMessage: Shopify private apps are deprecated. Use a Custom App `access_token` instead.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
